// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIFJVxz6MVCQbUC3X9FUd7oBdSiUiX_c',
    appId: '1:676303106632:web:95fd124846b555d3565e7d',
    messagingSenderId: '676303106632',
    projectId: 'mindlink-assignment-ab3ed',
    authDomain: 'mindlink-assignment-ab3ed.firebaseapp.com',
    storageBucket: 'mindlink-assignment-ab3ed.appspot.com',
    measurementId: 'G-2XHY2GY8Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5_jHyWJF-5ef-4qyGv0hUU2allW7vaA',
    appId: '1:676303106632:android:e09332214b694c4a565e7d',
    messagingSenderId: '676303106632',
    projectId: 'mindlink-assignment-ab3ed',
    storageBucket: 'mindlink-assignment-ab3ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsYzNMjtEmwO197wWq6MQKsPMVMBRtdQ',
    appId: '1:676303106632:ios:6c0ce1fa2fb5e9c1565e7d',
    messagingSenderId: '676303106632',
    projectId: 'mindlink-assignment-ab3ed',
    storageBucket: 'mindlink-assignment-ab3ed.appspot.com',
    iosBundleId: 'com.example.mindlinkAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsYzNMjtEmwO197wWq6MQKsPMVMBRtdQ',
    appId: '1:676303106632:ios:6c0ce1fa2fb5e9c1565e7d',
    messagingSenderId: '676303106632',
    projectId: 'mindlink-assignment-ab3ed',
    storageBucket: 'mindlink-assignment-ab3ed.appspot.com',
    iosBundleId: 'com.example.mindlinkAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmIFJVxz6MVCQbUC3X9FUd7oBdSiUiX_c',
    appId: '1:676303106632:web:67ffb1cae8f5523f565e7d',
    messagingSenderId: '676303106632',
    projectId: 'mindlink-assignment-ab3ed',
    authDomain: 'mindlink-assignment-ab3ed.firebaseapp.com',
    storageBucket: 'mindlink-assignment-ab3ed.appspot.com',
    measurementId: 'G-M6PR0937DE',
  );
}
